// data/plantsData.js
export const samplePlants = [
  {
    id: '1',
    name: 'SNAKE PLANT (Sansevieria spp.)',
    user: 'Jasleen Sandhu',
    time: '5h ago',
    location: 'California',
    tags: ['Indoor'],
    price: 19.99,
    image: require('./assets/images/snakeplant.jpg'),
  },
  {
    id: '2',
    name: 'ZZ PLANT (Zamioculcas zamiifolia)',
    user: 'Gurleen Kaur',
    time: '3h ago',
    location: 'Texas',
    tags: ['Popular', 'Indoor'],
    price: 24.99,
    image: require('./assets/images/ZZPlant.jpg'),
  },
  {
    id: '3',
    name: 'BOSTON FERN (Nephrolepis exaltata)',
    user: 'Ravneet Kaur',
    time: '1d ago',
    location: 'Florida',
    tags: ['Outdoor'],
    price: 14.50,
    image: require('./assets/images/BostonFern.jpg'),
  },
  {
    id: '4',
    name: 'TRADESCANTIA (Tradescantia spp.)',
    user: 'Nich',
    time: '2h ago',
    location: 'New York',
    tags: ['Garden', 'Popular'],
    price: 12.00,
    image: require('./assets/images/tradescantia.png'),
  },
  {
    id: '5',
    name: 'FIDDLE LEAF FIG (Ficus lyrata)',
    user: 'Sarah Green',
    time: '1h ago',
    location: 'Texas',
    tags: ['Outdoor'],
    price: 34.99,
    image: require('./assets/images/fiddleleaffig.jpeg'),
  },
  {
    id: '6',
    name: 'POTHOS (Epipremnum aureum)',
    user: 'John Kim',
    time: '6h ago',
    location: 'Nevada',
    tags: ['Indoor'],
    price: 10.00,
    image: require('./assets/images/pothos.jpg'),
  },
  {
    id: '7',
    name: 'ARECA PALM (Dypsis lutescens)',
    user: 'Priya Singh',
    time: '9h ago',
    location: 'Hawaii',
    tags: ['Indoor', 'Popular'],
    price: 29.99,
    image: require('./assets/images/areca.jpg'),
  },
  {
    id: '8',
    name: 'ALOE VERA (Aloe barbadensis)',
    user: 'Karan Mehta',
    time: '10h ago',
    location: 'Arizona',
    tags: ['Outdoor'],
    price: 8.50,
    image: require('./assets/images/aloe vera.jpg'),
  },
  {
    id: '9',
    name: 'RUBBER PLANT (Ficus elastica)',
    user: 'Leah Martinez',
    time: '4h ago',
    location: 'Georgia',
    tags: ['Indoor'],
    price: 22.99,
    image: require('./assets/images/rubberplant.jpg'),
  },
  {
    id: '10',
    name: 'PEACE LILY (Spathiphyllum spp.)',
    user: 'Carlos Diaz',
    time: '7h ago',
    location: 'Oregon',
    tags: ['Indoor', 'Popular'],
    price: 18.75,
    image: require('./assets/images/peacelily.jpg'),
  },
  {
    id: '11',
    name: 'JADE PLANT (Crassula ovata)',
    user: 'Emily Rogers',
    time: '12h ago',
    location: 'Utah',
    tags: ['Indoor'],
    price: 15.99,
    image: require('./assets/images/jadeplant.jpg'),
  },
  {
    id: '12',
    name: 'SPIDER PLANT (Chlorophytum comosum)',
    user: 'Noah Patel',
    time: '5h ago',
    location: 'Minnesota',
    tags: ['Indoor'],
    price: 9.99,
    image: require('./assets/images/spiderplant.jpg'),
  },
  {
    id: '13',
    name: 'ENGLISH IVY (Hedera helix)',
    user: 'Sophia Brown',
    time: '3h ago',
    location: 'Oregon',
    tags: ['Outdoor'],
    price: 12.25,
    image: require('./assets/images/englishivy.jpg'),
  },
  {
    id: '14',
    name: 'CALATHEA (Calathea spp.)',
    user: 'Luca Nguyen',
    time: '8h ago',
    location: 'Alberta',
    tags: ['Indoor', 'Popular'],
    price: 20.00,
    image: require('./assets/images/calathea.jpg'),
  },
  {
    id: '15',
    name: 'CROTON (Codiaeum variegatum)',
    user: 'Maya Kapoor',
    time: '6h ago',
    location: 'Mumbai',
    tags: ['Outdoor'],
    price: 11.50,
    image: require('./assets/images/croton.jpg'),
  },
  {
    id: '16',
    name: 'MONSTERA DELICIOSA',
    user: 'Ethan Chen',
    time: '4h ago',
    location: 'Singapore',
    tags: ['Indoor'],
    price: 35.00,
    image: require('./assets/images/monstera.jpg'),
  },
  {
    id: '17',
    name: 'DRACAENA (Dracaena spp.)',
    user: 'Lara White',
    time: '9h ago',
    location: 'Germany',
    tags: ['Indoor'],
    price: 17.25,
    image: require('./assets/images/dracaena.jpg'),
  },
  {
    id: '18',
    name: 'DUMB CANE (Dieffenbachia spp.)',
    user: 'Omar Reyes',
    time: '10h ago',
    location: 'Colombia',
    tags: ['Indoor'],
    price: 13.99,
    image: require('./assets/images/dumbcane.jpg'),
  },
  {
    id: '19',
    name: 'BAMBOO PALM (Chamaedorea seifrizii)',
    user: 'Yuki Aoki',
    time: '2h ago',
    location: 'Japan',
    tags: ['Indoor'],
    price: 21.50,
    image: require('./assets/images/bamboo.jpg'),
  },
  {
    id: '20',
    name: 'LAVENDER (Lavandula spp.)',
    user: 'Isla Harper',
    time: '3h ago',
    location: 'France',
    tags: ['Outdoor'],
    price: 7.99,
    image: require('./assets/images/lavender.jpg'),
  },
];
